# Generated by Django 2.2.5 on 2019-10-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='最长128个字符，用户唯一标示，但不是主键', max_length=64, unique=True, verbose_name='用户名')),
                ('hash_IMEI', models.CharField(help_text='手机标示码的哈希值，要求唯一标示（应当选取一个避免哈希碰撞的函数）', max_length=64, unique=True, verbose_name='IMEI码哈希值')),
                ('salt', models.CharField(help_text='这个盐值会随 timestamp 变化', max_length=64, verbose_name='盐值')),
                ('A_pwd', models.CharField(max_length=64)),
                ('B_pwd', models.CharField(max_length=64)),
                ('random_value1', models.CharField(max_length=64)),
                ('random_value2', models.CharField(max_length=64)),
                ('random_value3', models.CharField(max_length=64)),
            ],
        ),
    ]
