# Generated by Django 2.2.5 on 2019-10-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0003_usermodel_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='hash_IMEI',
            field=models.CharField(help_text='手机标示码的哈希值，要求唯一标示（应当选取一个避免哈希碰撞的函数）', max_length=64, verbose_name='IMEI码哈希值'),
        ),
    ]
